blastem: remove
Requires python2 and no release in over two years to resolve the
situation.

```
./img2tiles.py -s font_interlace_variable.spec font_interlace_variable.tiles
  File "/build/blastem-3d48cb0c28be/./img2tiles.py", line 78
    print len(colors), 'distinct 9-bit colors in image'
          ^
SyntaxError: invalid syntax
```